### PR TITLE
Modifying Dockerfile to use debian instead of ubuntu

### PR DESCRIPTION
**Pull request by Salem-1**
I am modifying the Dockerfile to use debian instead of ubuntu, because upon  installing the current ubutu dockerfile on 42 Imacs, students get mainfest for ubuntu focal not found

### CODE REVIEW

**Comment by Salem-1** [comment]
changing docker image to debian as getting error while installing current ubuntu image on 42 AD Imacs

**Comment by MisterTooh** [comment]
On the computer the ubuntu:focal was failing, could you test with the command docker pull ubuntu:focal?

**Comment by MisterTooh** [comment]
> changing docker image to debian as getting error while installing current ubuntu image on 42 AD Imacs

On the computer the ubuntu:focal was failing, could you test with the command docker pull ubuntu:focal?

**Comment by opsec-infosec** [comment]
I would like to resolve the issue with ubuntu:focal.  Debian has an issue with volume mapping on the 42 macs, it was the reason for selecting ubuntu.  I suspect there is something 42 is doing as I am able to pull, build and run the images without issue.  @Salem-1 can you get with MisterTooh and troubleshoot this issue.

**Comment by MisterTooh** [comment]
> I would like to resolve the issue with ubuntu:focal. Debian has an issue with volume mapping on the 42 macs, it was the reason for selecting ubuntu. I suspect there is something 42 is doing as I am able to pull, build and run the images without issue. @Salem-1 can you get with MisterTooh and troubleshoot this issue.

It appears to be a Docker version issue and should not require an image change. The issue appears to be a missing manifest when attempting to install the container in the older version in docker. It appears that newer versions of docker on some of the machines are running fine.

The better solution would be to request the Bocal to have the docker versions updated.

**Comment by AhmedAlfahal** [comment]
> On the computer the ubuntu:focal was failing, could you test with the command docker pull ubuntu:focal?
 I just tried that and it is showing this error 'Error response from daemon: manifest for ubuntu:focal not found'

**Comment by opsec-infosec** [comment]
I am closing this PR as it seems to be an issue with the version of Docker installed in the labs.

**Pull request closed without merging**
