### PR TITLE
Updated install script

### PR DESCRIPTION
**Pull request by MisterTooh**
Named directory in goinfre to com.docker.docker for continuity and clarity.

Directory to be created in ~/goinfre will now be named com.docker.docker

Changes made in install:
- Lines 53 - 54
- Lines 59 - 60

### CODE REVIEW

**Comment by MisterTooh** [comment]
Yes it works.


Tested.

**Review by opsec-infosec — CHANGES_REQUESTED** [review]
Can you remove the bgnd empty file...  Everything else looks good.

**Comment by MisterTooh** [comment]
> Can you remove the bgnd empty file... Everything else looks good.

Wilco! I'm not sure why it committed an empty file, the file doesn't appear empty on any of the repo's

**Comment by MisterTooh** [comment]
Closing due to ambiguous bgnd ambiguous change

**Pull request closed without merging**
